import * as dotenv from 'dotenv';
dotenv.config();

import * as fs from 'fs';
import * as path from 'path';

// ── File locations ──────────────────────────────────────────────
// Inputs are generated by the test run; output is the self-contained dashboard.
const RESULTS_PATH = path.join(__dirname, '..', 'test-results', 'results.json');
const HEALING_PATH = path.join(__dirname, 'healing-log.json');
const OUTPUT_DIR = path.join(__dirname, '..', 'dashboard');
const OUTPUT_PATH = path.join(OUTPUT_DIR, 'index.html');

// ── Shapes ──────────────────────────────────────────────────────
interface TestRow {
  name: string;
  status: string;      // 'passed' | 'failed' | 'skipped' | etc.
  duration: number;    // milliseconds
  error: string;       // empty when the test passed
}

interface HealEntry {
  timestamp: string;
  name: string;
  oldSelector: string;
  newSelector: string;
  url?: string;
}

// ── Safe JSON readers ───────────────────────────────────────────
// Inputs may be missing (e.g. tests never ran, no healing yet) — never throw.
function readJson<T>(file: string, fallback: T): T {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf-8')) as T;
  } catch {
    console.warn(`⚠️  Could not read ${path.relative(process.cwd(), file)} — using empty data.`);
    return fallback;
  }
}

// Walk the Playwright JSON report tree (suites nest arbitrarily) and flatten
// every spec into a single TestRow using its most recent result.
function collectTests(report: any): TestRow[] {
  const rows: TestRow[] = [];

  function walkSuite(suite: any) {
    for (const spec of suite.specs || []) {
      // A spec can have multiple tests (projects/retries); take the last result.
      const result = spec.tests?.[0]?.results?.slice(-1)[0];
      const errorMsg =
        result?.error?.message ||
        result?.errors?.[0]?.message ||
        '';

      rows.push({
        name: spec.title || '(untitled test)',
        status: result?.status || (spec.ok ? 'passed' : 'failed'),
        duration: result?.duration || 0,
        // Strip ANSI colour codes Playwright bakes into error messages.
        error: stripAnsi(errorMsg),
      });
    }
    for (const child of suite.suites || []) {
      walkSuite(child);
    }
  }

  for (const suite of report.suites || []) {
    walkSuite(suite);
  }
  return rows;
}

function stripAnsi(text: string): string {
  // eslint-disable-next-line no-control-regex
  return text.replace(/\[[0-9;]*m/g, '').trim();
}

// Escape user/test-derived strings before dropping them into HTML.
function esc(text: string): string {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms} ms`;
  return `${(ms / 1000).toFixed(2)} s`;
}

function formatTimestamp(iso: string): string {
  const d = new Date(iso);
  return isNaN(d.getTime()) ? iso : d.toLocaleString();
}

// ── Build the dashboard ─────────────────────────────────────────
function generate() {
  const report = readJson<any>(RESULTS_PATH, { suites: [] });
  const healing = readJson<HealEntry[]>(HEALING_PATH, []);

  const tests = collectTests(report);
  const total = tests.length;
  const passed = tests.filter(t => t.status === 'passed').length;
  const failed = tests.filter(t => t.status !== 'passed' && t.status !== 'skipped').length;
  const passRate = total > 0 ? Math.round((passed / total) * 100) : 0;

  // Prefer the report's own start time; fall back to "now".
  const lastRun = report.stats?.startTime
    ? formatTimestamp(report.stats.startTime)
    : new Date().toLocaleString();

  const html = renderHtml({ tests, total, passed, failed, passRate, lastRun, healing });

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, html, 'utf-8');

  console.log('\n📊 Dashboard generated');
  console.log('─────────────────────────────────────');
  console.log(`   Tests:     ${total}`);
  console.log(`   Passed:    ${passed}`);
  console.log(`   Failed:    ${failed}`);
  console.log(`   Pass rate: ${passRate}%`);
  console.log(`   Healing:   ${healing.length} entries`);
  console.log(`   Output:    ${path.relative(process.cwd(), OUTPUT_PATH)}\n`);
}

interface RenderData {
  tests: TestRow[];
  total: number;
  passed: number;
  failed: number;
  passRate: number;
  lastRun: string;
  healing: HealEntry[];
}

function renderHtml(d: RenderData): string {
  const testRows = d.tests.length
    ? d.tests
        .map(t => {
          const isFail = t.status !== 'passed' && t.status !== 'skipped';
          const icon = t.status === 'passed' ? '✅' : t.status === 'skipped' ? '⏭️' : '❌';
          return `
        <tr class="${isFail ? 'row-fail' : ''}">
          <td class="status-cell">${icon}</td>
          <td class="name-cell">${esc(t.name)}</td>
          <td class="duration-cell">${formatDuration(t.duration)}</td>
          <td class="error-cell">${t.error ? `<code>${esc(t.error)}</code>` : '—'}</td>
        </tr>`;
        })
        .join('')
    : `<tr><td colspan="4" class="empty">No test results found. Run the suite first.</td></tr>`;

  const healRows = d.healing.length
    ? d.healing
        .slice()
        .reverse() // newest first
        .map(
          h => `
        <tr>
          <td class="timestamp-cell">${esc(formatTimestamp(h.timestamp))}</td>
          <td class="name-cell">${esc(h.name)}</td>
          <td class="selector-cell">
            <code class="old">${esc(h.oldSelector)}</code>
            <span class="arrow">→</span>
            <code class="new">${esc(h.newSelector)}</code>
          </td>
        </tr>`
        )
        .join('')
    : `<tr><td colspan="3" class="empty">No self-healing events recorded.</td></tr>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>AI Test Framework Dashboard</title>
  <style>
    :root {
      --bg: #0f1117;
      --card: #1a1d27;
      --border: #2a2d3a;
      --text: #e5e7eb;
      --muted: #9ca3af;
      --green: #34d399;
      --red: #f87171;
      --blue: #60a5fa;
      --yellow: #fbbf24;
    }

    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      background: var(--bg);
      color: var(--text);
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.5;
      padding: 32px 24px;
    }

    .container { max-width: 1100px; margin: 0 auto; }

    /* ── Header ── */
    header { margin-bottom: 28px; }
    header h1 { font-size: 28px; font-weight: 700; letter-spacing: -0.5px; }
    header .timestamp { color: var(--muted); font-size: 14px; margin-top: 6px; }

    /* ── Stats row ── */
    .stats {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 16px;
      margin-bottom: 24px;
    }
    @media (max-width: 720px) { .stats { grid-template-columns: repeat(2, 1fr); } }

    .card {
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 20px;
    }
    .card .label {
      font-size: 13px;
      color: var(--muted);
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .card .value { font-size: 34px; font-weight: 700; margin-top: 8px; }
    .card.total .value { color: var(--blue); }
    .card.passed .value { color: var(--green); }
    .card.failed .value { color: var(--red); }
    .card.rate .value { color: var(--yellow); }

    /* ── Progress bar ── */
    .progress-wrap {
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 20px;
      margin-bottom: 32px;
    }
    .progress-header {
      display: flex;
      justify-content: space-between;
      font-size: 13px;
      color: var(--muted);
      margin-bottom: 10px;
    }
    .progress-track {
      background: #0f1117;
      border: 1px solid var(--border);
      border-radius: 999px;
      height: 16px;
      overflow: hidden;
    }
    .progress-fill {
      height: 100%;
      width: 0;
      border-radius: 999px;
      background: linear-gradient(90deg, var(--green), var(--blue));
      animation: grow 1.2s ease-out forwards;
    }
    @keyframes grow { from { width: 0; } to { width: ${d.passRate}%; } }

    /* ── Sections & tables ── */
    section { margin-bottom: 36px; }
    section h2 {
      font-size: 18px;
      font-weight: 600;
      margin-bottom: 14px;
      display: flex;
      align-items: center;
      gap: 8px;
    }

    .table-wrap {
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 12px;
      overflow: hidden;
    }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th {
      text-align: left;
      padding: 12px 16px;
      color: var(--muted);
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      border-bottom: 1px solid var(--border);
    }
    td {
      padding: 12px 16px;
      border-bottom: 1px solid var(--border);
      vertical-align: top;
    }
    tbody tr:last-child td { border-bottom: none; }
    tbody tr:nth-child(even) { background: rgba(255, 255, 255, 0.02); }
    tbody tr.row-fail { background: rgba(248, 113, 113, 0.08); }

    .status-cell { width: 48px; text-align: center; font-size: 16px; }
    .name-cell { font-weight: 500; }
    .duration-cell { color: var(--muted); white-space: nowrap; }
    .timestamp-cell { color: var(--muted); white-space: nowrap; }
    .empty { text-align: center; color: var(--muted); padding: 24px; }

    code {
      font-family: 'SF Mono', Monaco, 'Cascadia Code', monospace;
      font-size: 12.5px;
      background: rgba(255, 255, 255, 0.05);
      padding: 2px 6px;
      border-radius: 4px;
    }
    .error-cell code { color: var(--red); white-space: pre-wrap; word-break: break-word; }
    .selector-cell .old { color: var(--red); }
    .selector-cell .new { color: var(--green); }
    .selector-cell .arrow { color: var(--muted); margin: 0 6px; }

    /* ── Footer ── */
    footer {
      text-align: center;
      color: var(--muted);
      font-size: 13px;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid var(--border);
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>🤖 AI Test Framework Dashboard</h1>
      <p class="timestamp">Last run: ${esc(d.lastRun)}</p>
    </header>

    <div class="stats">
      <div class="card total">
        <div class="label">Total Tests</div>
        <div class="value">${d.total}</div>
      </div>
      <div class="card passed">
        <div class="label">Passed</div>
        <div class="value">${d.passed}</div>
      </div>
      <div class="card failed">
        <div class="label">Failed</div>
        <div class="value">${d.failed}</div>
      </div>
      <div class="card rate">
        <div class="label">Pass Rate</div>
        <div class="value">${d.passRate}%</div>
      </div>
    </div>

    <div class="progress-wrap">
      <div class="progress-header">
        <span>Pass Rate</span>
        <span>${d.passed} / ${d.total} passed</span>
      </div>
      <div class="progress-track">
        <div class="progress-fill"></div>
      </div>
    </div>

    <section>
      <h2>📋 Test Results</h2>
      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Status</th>
              <th>Test Name</th>
              <th>Duration</th>
              <th>Error</th>
            </tr>
          </thead>
          <tbody>${testRows}
          </tbody>
        </table>
      </div>
    </section>

    <section>
      <h2>🩹 Self-Healing Log</h2>
      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Timestamp</th>
              <th>Element</th>
              <th>Old Selector → New Selector</th>
            </tr>
          </thead>
          <tbody>${healRows}
          </tbody>
        </table>
      </div>
    </section>

    <footer>
      AI Test Framework — Built with Playwright + Claude API
    </footer>
  </div>
</body>
</html>
`;
}

generate();
